apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: dsv1
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8081'
spec:
  type: NodePort
  selector:
    app: dsv1  
  ports:
  - port: 8081
    targetPort: 8081 
