prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - name: example_alerts
        rules:
          - alert: HighCPUUsage
            expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
            for: 5 minutes
            labels:
              severity: critical
            annotations:
              summary: "High CPU usage detected on {{ $labels.instance }}"
              description: "{{ $labels.instance }} has had a CPU usage above 80% for more than 5 minutes."

