apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-usv1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usv1
  template:
    metadata:
      labels:
        app: usv1
    spec:
      containers:
      - name: usv1-ctn
        image: gurmindersingh5/flask:usv1
        ports:
        - containerPort: 8082
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: DB_PASS
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: DB_NAME