apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app: usv1
data:
  DB_USER: demo
  DB_PASS: password123
  DB_HOST: postgres-service.default.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: postgres
